In [1]:
# Vandermonde matrix

import numpy as np

def myVanderMat(X,N,f):
    if (f):
        return (np.flip(np.column_stack([X ** (N-1-i) for i in range(N)]),axis=1))
    else:
        return (np.column_stack([X ** (N-1-i) for i in range(N)]))


In [2]:
X = np.arange(5)
print(myVanderMat(X,5,True))

[[  1   0   0   0   0]
 [  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]]


In [3]:
print(myVanderMat(X,5,False))

[[  0   0   0   0   1]
 [  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]
